# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef34bfe1088e43208472ac20746eff357e07f5b192b8ef19a7f8e44c66ca46b34b60ee2721cd020fd3368cfc447afda91f574bb72429deb1dcc5816e701054df

test:
  secret_key_base: cc89d927c7a648d3b4b5b3b5815524d923ae1e81a8c32d99c5bc27e6f7997efe6c6a580c15c9968f6ed2b597fcb1df4d127348f9610973954a27f6d0669668ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
